version: '2'
services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - operationcode-psql
      - redis
    env_file:
      - .env

  operationcode-psql:
    image: postgres

  redis:
    image: redis:latest

  sidekiq:
    build: .
    command: sidekiq -C config/sidekiq.yml.erb
    volumes:
      - .:/app
    depends_on:
      - operationcode-psql
      - redis
    env_file:
      - .env

