# Each entry should contain the following:
# - name: <School Name>
#  url: <School URL>
#  logo: <Logo URL>
#  full_time:  Is your school full time? [true|false]
#  hardware_included: Does tuition include hardware? [true|false]
#  notes: <Addtional Comments> [optional]
#  locations:
#   - va_accepted: <GI Bill Accepted>
#     address1: <Address Line1>
#     address2: <Address Line2> [optional]
#     city: <School City>
#     state: <School State !!! Must be the 2 letter state code !!!>
#     zip: <School Zip>
#
#   Each entry must start on a new line with "- name:"
#   Each location must start on a new line with "- va_accepted:"
---
- name: Nashville Software School
  url: http://nashvillesoftwareschool.com/
  logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/code-schools-cooper-kyle/src/images/codeSchoolLogos/nss.jpg
  full_time: true
  hardware_included: false
  locations:
    - va_accepted: true
      address1: 500 Interstate Blvd South
      address2: Suite 300
      city: Nashville
      state: TN
      zip: 37210

- name: Dev Bootcamp
  url: http://devbootcamp.com
  logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/code-schools-cooper-kyle/src/images/codeSchoolLogos/dev_bootcamp.jpg
  full_time: true
  hardware_included: false
  locations:
    - va_accepted: false
      address1: 633 Folsom Street (at Hawthorne)
      address2: 6th Floor
      city: San Francisco
      state: CA
      zip: 94107
    - va_accepted: false
      address1: 351 West Hubbard St. (at Orleans)
      address2: Suite 701
      city: Chicago
      state: IL
      zip: 60605
    - va_accepted: false
      address1: 48 Wall St.
      address2: 15th Floor
      city: New York
      state: NY
      zip: 10005

- name: Galvanize
  url: https://new.galvanize.com
  logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/code-schools-cooper-kyle/src/images/codeSchoolLogos/galvanize.jpg
  full_time: true
  hardware_included: false
  locations:
    - va_accepted: false
      address1: 44 Tehama Street
      address2:
      city: San Francisco
      state: CA
      zip: 94015
    - va_accepted: true
      address1: Galvanize Denver - Golden Triangle
      address2: 1062 Delaware Street
      city: Denver
      state: CO
      zip: 80204
    - va_accepted: false
      address1: 1023 Walnut Street
      city: Boulder
      state: CO
      zip: 80302

- name: Hack Reactor
  url: http://www.hackreactor.com
  logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/code-schools-cooper-kyle/src/images/codeSchoolLogos/hack_reactor.jpg
  full_time: true
  hardware_included: false
  locations:
    - va_accepted: false
      address1: 944 Market St
      address2: 8th Floor
      city: San Francisco
      state: CA
      zip: 94102

- name: MakerSquare
  url: http://www.makersquare.com
  full_time: true
  hardware_included: false
  locations:
    - va_accepted: false
      address1: 611 Mission St, 2nd Floor
      city: San Francisco
      state: CA
      zip: 94105
    - va_accepted: false
      address1: "716 Congress Ave., #100"
      city: Austin
      state: TX
      zip: 78701

- name: Sabio
  url: http://sabio.la/veterans
  logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/code-schools-cooper-kyle/src/images/codeSchoolLogos/sabio.jpg
  full_time: true
  hardware_included: false
  notes: Sabio enables Operation Code veterans to learn the skills needed to secure a full-time position in an awesome tech company in six months all while earning college credits towards an undergraduate degree. The New GI Bill is an option for non-BA degree holders.
  locations:
    - va_accepted: true
      address1: 400 Corporate Pointe
      city: Culver City
      state: CA
      zip: 90230

- name: Tradecraft
  url: http://tradecrafted.com/
  logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/code-schools-cooper-kyle/src/images/codeSchoolLogos/tradecraft.jpg
  full_time: true
  hardware_included: false
  locations:
    - va_accepted: false
      address1: 400 Corporate Pointe
      city: San Fransisco
      state: CA
      zip: 94105

- name: RefactorU
  url: http://refactoru.com
  logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/code-schools-cooper-kyle/src/images/codeSchoolLogos/refactoru.jpg
  full_time: true
  hardware_included: false
  notes: RefactorU is proud and honored to announce that its Web Development Bootcamp has been approved by the <a href="http://www.benefits.va.gov/gibill/">Colorado State Approving Agency for Veterans Education & Training</a>. Students eligible for the The Post-9/11 GI Bill, Montgomery GI Bill (Active Duty/Selected Reserve), Reserve Educational Assistance Program, Veterans Educational Assistance Program, and Survivors’ and Dependents’ Educational Assistance Program may be eligible to apply those benefits to RefactorU’s Web Application Development Bootcamp.
  locations:
    - va_accepted: true
      address1: 5717 Arapahoe Avenue
      address2: "Suite #216"
      city: Boulder
      state: CO
      zip: 80303

- name: Turing School of Software & Design
  url: http://turing.io/
  logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/code-schools-cooper-kyle/src/images/codeSchoolLogos/turing.jpg
  full_time: true
  hardware_included: false
  locations:
    - va_accepted: true
      address1: 1510 Blake Street
      address2: "Suite #216"
      city: Denver
      state: CO
      zip: 80202

- name: The Iron Yard
  url: https://www.theironyard.com
  logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/code-schools-cooper-kyle/src/images/codeSchoolLogos/iron_yard.jpg
  full_time: true
  hardware_included: false
  locations:
    - va_accepted: false
      address1: 101 S. Garland Ave
      address2: Suite 102
      city: Orlando
      state: FL
      zip: 32801
    - va_accepted: false
      address1: "260 1st Ave S #300"
      city: Tampa Bay
      state: FL
      zip: 33701
    - va_accepted: false
      address1: 3423 Piedmont Road, NE
      city: Atlanta
      state: GA
      zip: 30305
    - va_accepted: false
      address1: 334 Blackwell Street
      address2: Suite B017
      city: Durham
      state: NC
      zip: 27701
    - va_accepted: false
      address1: 510 Mill Street
      city: Mount Pleasant
      state: SC
      zip: 29464
    - va_accepted: false
      address1: 411 University Ridge
      address2: Suite 220
      city: Greenville
      state: SC
      zip: 29601
    - va_accepted: false
      address1: 3601 South Congress Avenue
      address2: Suite c304
      city: Austin
      state: TX
      zip: 78704
    - va_accepted: false
      address1: 1121 Delano St.
      city: Houstin
      state: TX
      zip: 77003

- name: General Assembly
  url: https://generalassemb.ly
  logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/code-schools-cooper-kyle/src/images/codeSchoolLogos/general_assembly.jpg
  full_time: true
  hardware_included: false
  locations:
    - va_accepted: false
      address1: 675 Ponce de Leon Ave NE
      city: Atlanta
      state: GA
      zip: 30308
    - va_accepted: false
      address1: WeWork Seattle
      address2: 500 Yale Avenue N.
      city: Seattle
      state: WA
      zip: 98109

- name: Code Platoon
  url: http://www.codeplatoon.org
  logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/code-schools-cooper-kyle/src/images/codeSchoolLogos/code_platoon.jpg
  full_time: true
  hardware_included: false
  locations:
    - va_accepted: false
      address1: Downtown
      city: Chicago
      state: IL
      zip: 60654

- name: The Starter League
  url: http://www.starterleague.com/
  logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/code-schools-cooper-kyle/src/images/codeSchoolLogos/starter_league.jpg
  full_time: true
  hardware_included: false
  locations:
    - va_accepted: false
      address1: 30 N Racine Ave.
      city: Chicago
      state: IL
      zip: 60607

- name: Deep Dive Fullstack
  url: http://stemuluscenter.org/deep-dive-fullstack
  logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/code-schools-cooper-kyle/src/images/codeSchoolLogos/deep_dive_fullstack.jpg
  full_time: true
  hardware_included: false
  locations:
    - va_accepted: true
      address1: 20 1st Plaza Center NW
      city: Albuquerque, NM
      state: NM
      zip: 87102

- name: Fullstack Academy
  url: http://fullstackacademy.com
  logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/code-schools-cooper-kyle/src/images/codeSchoolLogos/fullstack_academy.jpg
  full_time: true
  hardware_included: false
  locations:
    - va_accepted: false
      address1: 5 Hanover Square
      address2: Floor 25
      city: New York
      state: NY
      zip: 10004
    - va_accepted: false
      address1: 222 W Merchandise Mart Plaza
      address2: "#1212"
      city: Chicago
      state: IL
      zip: 60654

- name: The Flatiron School
  url: http://flatironschool.com/
  logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/code-schools-cooper-kyle/src/images/codeSchoolLogos/flatiron_school.jpg
  full_time: true
  hardware_included: false
  locations:
    - va_accepted: false
      address1: 11 Broadway
      address2: Suite 260
      city: New York
      state: NY
      zip: 10004

- name: Thinkful
  url: http://www.thinkful.com
  logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/code-schools-cooper-kyle/src/images/codeSchoolLogos/thinkful.jpg
  full_time: true
  hardware_included: false
  locations:
    - va_accepted: false
      address1: 304 Hudson St
      address2: 5th floor
      city: New York
      state: NY
      zip: 10013

- name: Tradecraft
  url: http://tradecrafted.com
  full_time: true
  hardware_included: false
  locations:
    - va_accepted: false
      address1: 304 Hudson St
      address2: 5th floor
      city: New York
      state: NY
      zip: 10004

- name: Code Fellows
  url: https://www.codefellows.org
  logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/code-schools-cooper-kyle/src/images/codeSchoolLogos/code_fellows.jpg
  full_time: true
  hardware_included: false
  locations:
    - va_accepted: false
      address1: 920 SW Third Ave., 2nd Floor
      city: Portaland
      state: OR
      zip: 97204
    - va_accepted: true
      address1: 511 Boren Ave N.
      city: Seattle
      state: WA
      zip: 98109

- name: Epicodus
  url: http://www.epicodus.com/
  logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/code-schools-cooper-kyle/src/images/codeSchoolLogos/epicodus.jpg
  full_time: true
  hardware_included: false
  notes: (Also see, <a href="http://www.learnhowtoprogram.com/lessons/learn-how-to-program">Learn how to program</a>.)
  locations:
    - va_accepted: false
      address1: 208 SW 5th Ave
      city: Portaland
      state: OR
      zip: 97214

- name: PDX Code Guild
  url: http://pdxcodeguild.com
  logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/code-schools-cooper-kyle/src/images/codeSchoolLogos/pdx_code_guild.jpg
  full_time: true
  hardware_included: false
  locations:
    - va_accepted: false
      address1: 2626 SW Corbett Ave
      address2: Suite 100
      city: Portaland
      state: OR
      zip: 97201

- name: Ada Developers Academy
  url: http://adadevelopersacademy.org
  logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/code-schools-cooper-kyle/src/images/codeSchoolLogos/ada_developers.jpg
  full_time: true
  hardware_included: false
  notes: <strong>Women-only and tuition-free</strong>. One-year program.
  locations:
    - va_accepted: false
      address1: Downtown Seattle
      city: Seattle
      state: WA
      zip: 98109

- name: Operation Spark
  url: https://operationspark.org
  logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/code-schools-cooper-kyle/src/images/codeSchoolLogos/operation_spark.jpg
  full_time: true
  hardware_included: false
  locations:
    - va_accepted: false
      address1: 748 Camp Street, 2nd floor
      city: New Orleans
      state: LA
      zip: 70130

- name: Startup Institute
  url: https://www.startupinstitute.com/boston/
  logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/code-schools-cooper-kyle/src/images/codeSchoolLogos/startup_institute.jpg
  full_time: true
  hardware_included: false
  locations:
    - va_accepted: false
      address1: 50 Milk Street, 14th Floor
      city: Boston
      state: MA
      zip: 02109
    - va_accepted: false
      address1: 25 Broadway, 10th Floor
      city: New York City
      state: NY
      zip: 10004

- name: Codeup
  url: http://codeup.com/
  logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/code-schools-cooper-kyle/src/images/codeSchoolLogos/codeup.jpg
  full_time: true
  hardware_included: false
  locations:
    - va_accepted: true
      address1: "600 Navarro St., #350"
      city: San Antonio
      state: TX
      zip: 78205

- name: DeVry Bootcamp
  url: http://partner.devry.edu/bootcamp/
  logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/code-schools-cooper-kyle/src/images/codeSchoolLogos/devry_bootcamp.jpg
  full_time: true
  hardware_included: true
  locations:
    - va_accepted: false
      address1: 1870 W 122nd Ave
      city: Westminster
      state: CO
      zip: 80234

- name: App Academy
  url: https://www.appacademy.io/
  logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/code-schools-cooper-kyle/src/images/codeSchoolLogos/app_academy.jpg
  full_time: true
  hardware_included: false
  notes: Deferred financing system (20% of your first year's salary)
  locations:
    - va_accepted: false
      address1: 160 Spear St
      city: San Francisco
      state: CA
      zip: 94105

- name: Tech Elevator
  url: http://www.techelevator.com/
  logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/code-schools-cooper-kyle/src/images/codeSchoolLogos/tech_elevator.jpg
  full_time: true
  hardware_included: true
  locations:
    - va_accepted: false
      address1: 7100 Euclid Ave
      city: Cleveland
      state: OH
      zip: 44103
    - va_accepted: false
      address1: 1275 Kinnear Rd
      address2: Suite 121
      city: Columbus
      state: OH
      zip: 43212

- name: Code Immersives (New York City, New York)
  url:  https://web1.codeimmersives.com/
  full_time: true
  hardware_included: true
  notes: (Also see, <a href="https://web1.codeimmersives.com/students/veterans"> Veteran Student </a>.)
  locations:
    - va_accepted: true
      address1: 630 9th Ave
      address2: Suite 901
      city: New York
      state: NY
      zip: 10036

- name: Coding Dojo
  url: http://www.codingdojo.com
  full_time: true
  hardware_included: false
  locations:
    - va_accepted: false
      address1: 1775 GREENSBORO STATION PLACE
      address2: Suite 210
      city: McLean
      state: VA
      zip: 22102
    - va_accepted: false
      address1: 1920 ZANKER ROAD
      address2: Suite 20
      city: San Jose
      state: CA
      zip: 95112
    - va_accepted: false
      address1: 10777 MAIN ST
      address2: Suite 300
      city: Bellevue
      state: WA
      zip: 98004
    - va_accepted: false
      address1: 175 E OLIVE AVE
      address2: 3rd Fl
      city: Burbank
      state: CA
      zip: 91502
    - va_accepted: false
      address1: 900 JACKSON ST
      address2: Suite 410
      city: Dallas
      state: TX
      zip: 75202
    - va_accepted: false
      address1: 213 WEST INSTITUTE PLACE
      address2: Suite 610
      city: Chicago
      state: IL
      zip: 60610

- name: Coder Camps
  url: https://www.codercamps.com
  full_time:  true
  hardware_included: false
  notes: Coder Camps offers two paths to taking a Full Stack Web Development course. A <strong>12 week</strong> full time Immersive on-campus/online program and a <strong>24 week</strong> part time Structured Online program.  Active military and veterans receive a <strong>20 percent discount</strong> on tuition, we are able to accept Chapter 31 &amp; 35 benefits.
  locations:
    - va_accepted: false
      address1: 8444 N 90TH ST
      address2: Suite 110
      city: Scottsdale
      state: AZ
      zip: 85258
